on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: bun-${{ hashFiles('bun.lock') }}
          restore-keys: bun-

      - name: Install modules
        run: bun install

      - name: ESLint
        run: bun run eslint '**/*.ts' --fix

      - name: Prettier
        run: bun run prettier --check .
